package com.github.jaceko.circuitswitcher.it.jaxws.client.hello_world_soap_http;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-09-25T21:13:40.438+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://apache.org/hello_world_soap_http", name = "Greeter")
@XmlSeeAlso({com.github.jaceko.circuitswitcher.it.jaxws.client.hello_world_soap_http.types.ObjectFactory.class})
public interface Greeter {

    @WebResult(name = "responseText", targetNamespace = "http://apache.org/hello_world_soap_http/types")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://apache.org/hello_world_soap_http/types", className = "org.apache.hello_world_soap_http.types.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://apache.org/hello_world_soap_http/types", className = "org.apache.hello_world_soap_http.types.SayHiResponse")
    public java.lang.String sayHi();
}
